/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "leveldb/db.h"
/* Header for class leveldb_sax_db */

#ifndef _Included_leveldb_sax_db
#define _Included_leveldb_sax_db
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     leveldb_sax_db
 * Method:    leaftimekey_from_tskey
 * Signature: ([BIJZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_leveldb_1sax_db_leaftimekey_1from_1tskey
    (JNIEnv *, jobject, jbyteArray, jint, jlong, jboolean);

/*
 * Class:     leveldb_sax_db
 * Method:    leaftimekey_sort
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_leveldb_1sax_db_leaftimekey_1sort
    (JNIEnv *, jobject, jbyteArray);
/*
 * Class:     leveldb_sax_db
 * Method:    saxt_from_ts
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_leveldb_1sax_db_saxt_1from_1ts
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     leveldb_sax_db
 * Method:    paa_saxt_from_ts
 * Signature: ([B[B[F)V
 */
JNIEXPORT void JNICALL Java_leveldb_1sax_db_paa_1saxt_1from_1ts
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jfloatArray);


/*
 * Class:     leveldb_sax_db
 * Method:    dist_ts
 * Signature: ([B[B)F
 */
JNIEXPORT jfloat JNICALL Java_leveldb_1sax_db_dist_1ts
    (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     leveldb_sax_db
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_leveldb_1sax_db_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     leveldb_sax_db
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_leveldb_1sax_db_close
  (JNIEnv *, jobject);

/*
 * Class:     leveldb_sax_db
 * Method:    init
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_leveldb_1sax_db_init
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     leveldb_sax_db
 * Method:    put
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_leveldb_1sax_db_put
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     leveldb_sax_db
 * Method:    Get
 * Signature: ([BZII[J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_leveldb_1sax_db_Get
  (JNIEnv *, jobject, jbyteArray, jboolean, jint, jint, jlongArray);

/*
 * Class:     leveldb_sax_db
 * Method:    Get_exact
 * Signature: ([BII[J[B[J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_leveldb_1sax_db_Get_1exact
    (JNIEnv *, jobject, jbyteArray, jint, jint, jlongArray, jbyteArray, jlongArray);

/*
 * Class:     leveldb_sax_db
 * Method:    unref_am
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_leveldb_1sax_db_unref_1am
  (JNIEnv *, jobject, jint);

/*
 * Class:     leveldb_sax_db
 * Method:    unref_st
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_leveldb_1sax_db_unref_1st
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
